# Generated by Django 5.0.6 on 2024-06-29 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mobile_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{7,15}$', message='Phone number must be between 7 and 15 digits.')]),
        ),
    ]
