# Generated by Django 5.0.6 on 2024-07-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_entry_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='fourth_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='third_name',
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='No Name', max_length=25),
        ),
    ]
